{
  "hash": "39add13037af1c9aabe83d5dd30efd82",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"7. ES Core Relative Allocation: implementation and evidence\"\n---\n\n\n\nThe preceding six sections built a framework for evaluating investment return sources, constructing portfolios, and assessing whether active programs justify their place alongside a passive core. This section applies that framework to a specific systematic strategy — the ES Core Relative Allocation — documenting its instrument universe, design rationale, robustness evidence, and early live track record on Darwinex Zero.\n\n## Instrument universe and core design\n\nThe strategy trades six futures contracts: ES (S&P 500), NQ (Nasdaq-100), RTY (Russell 2000), GC (Gold), SI (Silver), and ZN (10-year Treasury). All six are USD-denominated and trade on regulated U.S. exchanges.\n\nThe primary constraint shaping the universe is the Darwinex Zero platform, which is the live deployment environment. Darwinex Zero provides access to a $1 million account with investor capital at stake. Futures contracts carry large notional values, and the set of instruments practically tradeable within this infrastructure at the required position sizes is the binding constraint on universe construction. All contracts must be USD-denominated — mixing currency exposures would introduce a foreign exchange risk layer that is not part of the strategy's design intent.\n\nWithin those constraints, the universe was built around one organizing principle: each instrument should represent a distinct economic exposure that belongs in a long-term portfolio allocation. Short-term interest rate futures are not available on the platform. Commodity sub-sector contracts were excluded because they are not intended to be held as long-term risk premia — they are instruments designed for shorter-horizon positioning that would be inconsistent with the strategy's long-term allocation framework.\n\nThe three equity contracts each represent a meaningfully different segment of the U.S. economy. ES provides exposure to the broad U.S. equity market — large and mid-cap businesses across all sectors, weighted by market capitalization. NQ concentrates exposure in the Nasdaq-100, heavily weighted toward technology, software, semiconductors, and other innovation-driven businesses with long-duration earnings profiles. RTY provides exposure to U.S. small-cap domestically oriented businesses whose returns are more sensitive to domestic economic conditions and less correlated with global growth cycles than large-cap indices. Gold and silver provide real asset exposure — stores of value whose behavior differs from financial assets, particularly during currency stress and late-cycle environments. The ten-year Treasury provides duration — long-dated fixed income exposure that has historically served as a portfolio diversifier during equity stress in disinflationary regimes.\n\nA global equity futures contract would have been a natural addition — replacing ES as the core would have broadened geographic diversification and reduced the strategy's dependence on U.S. equity specifically. This remains a design priority, but global equity futures are not currently available within the Darwinex Zero platform infrastructure.\n\n**Why ES is the core.** U.S. large-cap equity has been the most reliably positive long-run risk premium available to investors — the equity risk premium is the foundation on which every other return source in the universe is measured and evaluated. ES is also the benchmark against which every alternative's relative performance is assessed: the allocation signal measures how consistently each alternative is outperforming the equity core on a risk-adjusted basis, which requires a stable and liquid reference instrument. The permanent equity core ensures the strategy participates in the growth regime that historically accounts for the majority of compounded long-run return. The objective is strong long-run compounding — the design accepts bear market drawdowns as the necessary cost of sustained equity participation.\n\n## Strategy design and the role of leverage\n\nThe ES Core Relative Allocation maintains a permanent allocation to ES as the equity core and dynamically allocates up to 50 percent of the portfolio to the five alternative instruments based on their risk-adjusted performance relative to ES.\n\nThe allocation process operates at daily frequency. The signal evaluates each instrument's recent risk-adjusted performance history and determines both the size of each position and the proportion of the portfolio it receives. Strong-performing alternatives receive larger allocations; weak-performing alternatives are reduced toward zero. The ES core always holds the residual weight — ensuring net long equity exposure at all times. Allocations are smoothed to reduce unnecessary turnover, and a no-trade band prevents rebalancing when signal changes are small relative to the existing position.\n\nThe strategy incorporates a dynamic volatility targeting mechanism. Position sizes are scaled in proportion to recent measured downside volatility, so that each instrument contributes a roughly consistent level of realized risk to the portfolio regardless of its current volatility regime. When an instrument becomes more volatile its position size is reduced; when it becomes less volatile the position expands. This mechanism ensures that the strategy's overall risk profile remains relatively stable across different market conditions.\n\nLeverage is not an optional feature — it is structurally necessary. Futures contracts require margin rather than full capital, and the volatility targeting mechanism systematically determines how much notional exposure each dollar of capital should support. In high-conviction, low-volatility environments the strategy runs above 1x notional leverage; in uncertain or high-volatility environments it contracts toward or below 1x. The objective of dynamic leverage is not to maximize return at any given moment but to maintain a consistent risk profile across changing conditions. The strategy is a levered, dynamically sized futures program whose long-run return is the product of sustained participation in multiple risk premia — not a single static equity position.\n\nSpecific signal parameters are not disclosed here. Publishing exact parameters would accelerate their decay as similar strategies adopted the same values — the adaptive markets logic from section 2 applies directly.\n\n## Backtest results\n\nThe strategy was backtested from 2002 to March 2026 using Yahoo Finance continuous futures data. All signals are lagged one day to prevent look-ahead bias. The common analysis start date is 2003-08-18, reflecting the warm-up period required for the longest signal windows to initialize.\n\n| Metric | Strategy | ES benchmark | ES-only (levered) |\n|--------|----------|--------------|-------------------|\n| Total return | 3,699% | 601% | 2,250% |\n| CAGR | 16.8% | 8.6% | 14.3% |\n| Ann. volatility | 22.3% | 19.0% | 23.4% |\n| Sharpe ratio | **0.807** | 0.530 | 0.689 |\n| Sortino ratio | **1.095** | 0.745 | 0.936 |\n| Max drawdown | **−30.2%** | −57.1% | −42.4% |\n\nThe strategy produces a Sharpe of 0.807 and Sortino of 1.095 over the full backtest period, compared to 0.530 and 0.745 for the ES buy-and-hold benchmark. The maximum drawdown of −30.2% compares favorably to −57.1% for the benchmark and −42.4% for the levered ES-only alternative.\n\nThe comparison against the levered ES-only alternative is the more informative benchmark. It isolates the contribution of tactical allocation: the ES-only levered alternative applies the same dynamic leverage but holds only ES, producing a CAGR of 14.3% and Sharpe of 0.689. The additional 2.5 percentage points of CAGR and 0.118 Sharpe points above that baseline reflect the value of rotating across the alternative instruments rather than concentrating in a single equity contract.\n\n## Parameter robustness\n\nA strategy that performs well only at its exact design parameters is not a robust investment program but a result specific to one set of choices. Two complementary analyses test whether the strategy holds beyond its baseline configuration.\n\nA one-at-a-time sensitivity analysis tested each of the six key design parameters across five values ranging from −50% to +50% of the baseline. The Sharpe ratio remained above 0.75 for four of the six parameters across the full tested range. Two parameters — the EMA smoothing span and the no-trade band — showed essentially no sensitivity. The most sensitive parameter was the signal lookback window, which showed a clear directional pattern: shorter windows consistently outperformed longer ones.\n\nThe Monte Carlo analysis tested 50 randomly sampled combinations across the full six-dimensional parameter space simultaneously, evaluated over a common analysis start date to ensure fair comparison. The Sharpe threshold of 0.70 was chosen as a conservative minimum — it represents a level at which the strategy would still produce meaningful risk-adjusted return well above the passive equity benchmark's Sharpe of 0.53, justifying the operational complexity of a futures-based program. 52% of combinations exceeded this threshold, and the baseline configuration sat at the 98th percentile of the distribution.\n\n::: {#fe3b7a20 .cell execution_count=2}\n\n::: {.cell-output .cell-output-display}\n![Distribution of Sharpe ratios across 50 randomly sampled parameter combinations evaluated over a common start date (2003-08-18). The baseline configuration (dashed line, Sharpe 0.807) sits at the 98th percentile. 52% of combinations exceed the Sharpe 0.70 threshold. Source: Author calculations.](07_strategy_implementation_files/figure-html/cell-3-output-1.png){width=883 height=448}\n:::\n:::\n\n\nThe most important robustness finding is the dominant sensitivity to the signal lookback window — correlation of −0.77 between window length and Sharpe across the Monte Carlo sample. The current baseline may not be optimal here, and a shorter window is a candidate for future revision once the live deployment provides sufficient out-of-sample evidence.\n\n::: {#5971624e .cell execution_count=3}\n\n::: {.cell-output .cell-output-display}\n![Monte Carlo equity paths — 50 parameter combinations over the common analysis period from 2003-08-18. Black = baseline. Color = Sharpe ratio (green = higher, red = lower). The 5th–95th percentile band is shaded. All combinations produce positive compounded returns throughout the sample. Source: Author calculations.](07_strategy_implementation_files/figure-html/cell-4-output-1.png){width=595 height=499}\n:::\n:::\n\n\n## Regime decomposition\n\nThe strategy's performance varies substantially across macro conditions. Each trading day in the backtest is classified into one of four regimes using publicly available data: Equity Bear (trailing 12-month market return below −10% or VIX above 30, taking priority over all other conditions), Inflation (CPI year-on-year above 4% and rising), Equity Bull (trailing 12-month return above 15%), and Neutral (all remaining days). The priority ordering ensures that bear conditions are correctly identified even when they coincide with elevated inflation.\n\n::: {#c3c49b47 .cell execution_count=4}\n\n::: {.cell-output .cell-output-display}\n![Macro regime classification across the backtest period, 2003–2026. Top panel: strategy equity curve with regime shading. Panels below: Fama-French market factor 12-month return with S&P 500 shown for reference where available, VIX, and CPI year-on-year. Source: Fama-French Data Library, FRED (VIXCLS, CPIAUCSL), author calculations.](07_strategy_implementation_files/figure-html/cell-5-output-1.png){width=614 height=499}\n:::\n:::\n\n\n| Regime | Days | % Sample | CAGR | Sharpe | Max DD | Win rate |\n|--------|------|----------|------|--------|--------|----------|\n| Equity Bull | 837 | 14.1% | +82.2% | 3.27 | −21.8% | 58.9% |\n| Equity Bear | 657 | 11.0% | −39.1% | −2.03 | −22.5% | 46.9% |\n| Inflation | 575 | 9.7% | +7.5% | 0.34 | −28.8% | 53.2% |\n| Neutral | 3884 | 65.2% | +19.9% | 0.90 | −24.5% | 56.9% |\n\nThe strategy earns its return across two complementary regimes. The Neutral regime — 65% of all trading days — produces a Sharpe of 0.90 and a CAGR of 19.9%, forming the backbone of compounded long-run performance. Equity Bull periods produce an exceptional Sharpe of 3.27 as the dynamic leverage mechanism amplifies equity participation during strong trending conditions. Together these two regimes account for 79% of the sample and all positive contribution.\n\nThe Equity Bear regime is the strategy's primary structural weakness. During the 657 bear-regime days the strategy lost at an annualized rate of −39.1% with a Sharpe of −2.03. This is a direct consequence of the backward-looking signal design: the allocation mechanism requires sustained relative underperformance before it reduces equity exposure materially. In sharp, rapid bear markets the strategy experiences full equity drawdown before the signal has time to rotate. This is not a parameter optimization problem — it is a structural feature of any signal that measures performance over a multi-month lookback window. An investor in this strategy must accept that bear market losses are the cost of sustained equity participation across the 79% of conditions when the strategy is designed to perform.\n\n::: {#533f22e5 .cell execution_count=5}\n\n::: {.cell-output .cell-output-display}\n![Strategy performance by macro regime: annualized CAGR, Sharpe ratio, maximum drawdown, and daily win rate. The Neutral regime (grey) is the backbone of long-run return. Bear regime losses (red) are structural — a consequence of backward-looking signal design rather than a parameter flaw. Source: FRED, author calculations.](07_strategy_implementation_files/figure-html/cell-6-output-1.png){width=754 height=499}\n:::\n:::\n\n\nThe Inflation regime produces a mediocre 7.5% CAGR and 0.34 Sharpe. Understanding why requires distinguishing between two things the strategy does with gold. Gold carries a persistent and meaningful beta throughout the backtest — the signal allocates to it whenever it outperforms ES on a risk-adjusted basis over the measurement window, which occurs during equity stress, late-cycle environments, and some inflation periods. However during inflation episodes where equity continues to perform adequately in nominal terms — as in 2021, when rising inflation coincided with continued equity gains — the signal stays in equity because ES is still outperforming gold on the backward-looking measurement. The strategy responds to realized relative performance, not to inflation forecasts. Gold therefore appears when equity stress and inflation coincide but is underallocated when inflation rises without immediate equity deterioration. This is a known constraint of any reactive signal design, not a contradiction in the return sources.\n\n## Return sources\n\nThe strategy's return comes from three sources.\n\nThe dominant source is equity market exposure. The strategy maintains permanent net long equity through its ES core, and this exposure to the equity risk premium is the foundation of its long-run return. This is structural beta — the return available to any investor with sustained equity participation.\n\nThe second source is real asset exposure, primarily through gold. The allocation signal carries a persistent gold beta throughout the backtest, reflecting the signal's tendency to rotate toward gold during equity stress and late-cycle environments when gold outperforms ES on a risk-adjusted basis. This is a reactive rather than predictive allocation — the strategy does not anticipate gold's outperformance but responds to it as it emerges.\n\nThe third source is the dynamic allocation signal itself — the incremental return above a static long equity and gold position. Full-sample analysis estimates this contribution at approximately 6 percentage points of annualized return with a t-statistic that is meaningful but not conclusive given the backtest length. This is the component that requires ongoing validation in live deployment and that cannot be fully attributed to known systematic factors.\n\nThe strategy is a leveraged equity program with a real asset overlay and a tactical rotation mechanism. Its market exposure is dynamic — averaging approximately 1.25 times the equity market across the backtest, rising above 2.0 during high-conviction trending environments and contracting toward 0.2 during weak signal periods. It is not a market-neutral or low-beta program.\n\n## Live deployment\n\nThe ES Core Relative Allocation has been deployed live on Darwinex Zero under the ticker UJNU since 5 March 2026. The live track record is available at [https://www.darwinexzero.com/darwin/UJNU/performance](https://www.darwinexzero.com/darwin/UJNU/performance).\n\nDarwinex Zero applies a VaR normalization filter to all strategy returns, standardizing the published track record to a target monthly VaR of 6.5%. The published performance will therefore differ from the underlying strategy returns whenever the strategy's actual volatility diverges materially from that target. Investors comparing the published DARWIN performance to the backtest results in this document should account for this normalization. Direct replication of the underlying strategy outside of Darwinex Zero would require a regulated fund structure with futures execution infrastructure. For individual investors, Darwinex Zero is currently the only accessible vehicle for participating in the strategy's performance.\n\nAt the time of writing the live track record is approximately eight weeks old — insufficient for any statistical inference about performance quality. What it confirms is that the implementation is functioning as designed. The appropriate evaluation horizon is a minimum of 24 months across at least two distinct macro regimes. The regime classification framework above provides the diagnostic lens for interpreting that performance as it accumulates.\n\n## The framework applied\n\nEvery design decision in the ES Core Relative Allocation traces directly to a specific section of this framework. The return source taxonomy from section 3 explains what the strategy harvests. The portfolio construction principles from section 4 explain how exposures are sized and combined. The expected return framework from section 5 explains how to evaluate whether current conditions justify the positions. The cost hierarchy from section 6 explains where the strategy sits in a broader portfolio.\n\nThe standards are stated in advance. The evidence is presented honestly. The gaps are acknowledged. What remains is the live record.\n\n",
    "supporting": [
      "07_strategy_implementation_files"
    ],
    "filters": [],
    "includes": {}
  }
}