<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>7. ES Core Relative Allocation: implementation and evidence – RR Strategy Research</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-a0f9fd0d421825b736dc1bbcbcba2219.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">RR Strategy Research</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./01_markets_prices_expectations.html"> 
<span class="menu-text">1. Prices &amp; Expectations</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./02_signals_forecasting_outperformance.html"> 
<span class="menu-text">2. Signals</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./03_return_sources_factor_structure.html"> 
<span class="menu-text">3. Return Sources</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./04_portfolio_construction.html"> 
<span class="menu-text">4. Portfolio Construction</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./05_expected_returns.html"> 
<span class="menu-text">5. Expected Returns</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./06_core_allocation_active_programs.html"> 
<span class="menu-text">6. Core Allocation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./07_strategy_implementation.html" aria-current="page"> 
<span class="menu-text">7. Strategy</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul>
  <li><a href="#the-instrument-universe" id="toc-the-instrument-universe" class="nav-link active" data-scroll-target="#the-instrument-universe">The instrument universe</a></li>
  <li><a href="#why-es-is-the-core" id="toc-why-es-is-the-core" class="nav-link" data-scroll-target="#why-es-is-the-core">Why ES is the core</a></li>
  <li><a href="#strategy-design" id="toc-strategy-design" class="nav-link" data-scroll-target="#strategy-design">Strategy design</a></li>
  <li><a href="#backtest-results" id="toc-backtest-results" class="nav-link" data-scroll-target="#backtest-results">Backtest results</a></li>
  <li><a href="#parameter-robustness" id="toc-parameter-robustness" class="nav-link" data-scroll-target="#parameter-robustness">Parameter robustness</a></li>
  <li><a href="#regime-decomposition" id="toc-regime-decomposition" class="nav-link" data-scroll-target="#regime-decomposition">Regime decomposition</a></li>
  <li><a href="#return-sources" id="toc-return-sources" class="nav-link" data-scroll-target="#return-sources">Return sources</a></li>
  <li><a href="#live-deployment" id="toc-live-deployment" class="nav-link" data-scroll-target="#live-deployment">Live deployment</a></li>
  <li><a href="#the-framework-applied" id="toc-the-framework-applied" class="nav-link" data-scroll-target="#the-framework-applied">The framework applied</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">7. ES Core Relative Allocation: implementation and evidence</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>The preceding six sections built a framework for evaluating investment return sources, constructing portfolios, and assessing whether active programs justify their place alongside a passive core. This section applies that framework to a specific systematic strategy — the ES Core Relative Allocation — documenting its design, its robustness evidence, and its early live track record on Darwinex Zero.</p>
<section id="the-instrument-universe" class="level2">
<h2 class="anchored" data-anchor-id="the-instrument-universe">The instrument universe</h2>
<p>The strategy trades six futures contracts: ES (S&amp;P 500), NQ (Nasdaq-100), RTY (Russell 2000), GC (Gold), SI (Silver), and ZN (10-year Treasury).</p>
<p>The primary constraint is the Darwinex Zero platform, which is the live deployment environment. Darwinex Zero provides access to a $1 million virtual account with investor capital at stake — a meaningful operational context. Futures contracts have large notional values, and the set of instruments practically tradeable within this infrastructure is the binding constraint on universe construction. All six contracts are USD-denominated, which is a second hard requirement: mixing currency exposures would introduce a foreign exchange risk layer that is not part of the strategy’s design intent.</p>
<p>Within those constraints, liquidity was the next filter. All six instruments trade on regulated U.S. exchanges with deep intraday markets, tight spreads, and sufficient open interest to execute the strategy’s position sizes without material market impact. Several otherwise attractive contracts — short-term interest rate futures, commodity sub-sectors — were excluded on liquidity grounds relative to the notional sizes required.</p>
<p>The universe reflects a deliberate attempt at asset class breadth within a long-term portfolio context. The three equity contracts span large-cap growth (NQ), broad large-cap (ES), and small-cap (RTY). Gold and silver provide real asset exposure. The ten-year Treasury provides duration. Each represents a distinct economic exposure that would belong in a considered long-term allocation. A global equity futures contract would have been a natural addition but is not available within the current platform infrastructure.</p>
</section>
<section id="why-es-is-the-core" class="level2">
<h2 class="anchored" data-anchor-id="why-es-is-the-core">Why ES is the core</h2>
<p>The strategy maintains U.S. large-cap equity as its permanent core exposure for three reasons.</p>
<p>The first is the equity risk premium. Over the long run, equity ownership in productive businesses has been the most reliably positive risk premium available to investors. The equity risk premium is the foundation on which every other return source in the universe is measured and evaluated.</p>
<p>The second is the role of ES as the benchmark for relative performance measurement. The strategy’s tactical allocation signal measures how each alternative asset is performing relative to ES on a risk-adjusted basis. This requires a stable, liquid reference against which relative performance is meaningful. ES — the most liquid futures contract in the world — is the natural choice.</p>
<p>The third is that maintaining a permanent equity core ensures the strategy participates in the growth regime that historically accounts for the majority of long-run compounded return. A strategy that reduces equity to zero during adverse conditions may protect capital in the short term but risks missing the recovery that follows. The design accepts bear market drawdowns as the cost of sustained equity participation.</p>
</section>
<section id="strategy-design" class="level2">
<h2 class="anchored" data-anchor-id="strategy-design">Strategy design</h2>
<p>The ES Core Relative Allocation is a systematic multi-asset futures strategy. It maintains a permanent allocation to ES as the equity core and dynamically allocates up to 50 percent of the portfolio to alternative instruments based on their risk-adjusted performance relative to the core.</p>
<p>The allocation process operates at daily frequency. Each instrument’s recent risk-adjusted performance is evaluated and used to determine both the size of its position and the proportion of the portfolio it receives. Strong-performing alternatives receive larger allocations; weak-performing alternatives are reduced toward zero. The ES core always holds the residual — one minus the sum of alternative weights — ensuring net long equity exposure at all times. Allocations are smoothed to reduce unnecessary turnover, and a no-trade band prevents rebalancing on small signal changes.</p>
<p>The strategy is designed to behave differently across macro regimes. In sustained equity bull markets it participates fully through its ES core and benefits from the performance of NQ and RTY during growth-driven periods. In risk-off environments gold and Treasury duration are expected to outperform ES on a relative basis, triggering a rotation toward those instruments. The backward-looking nature of the signal means this rotation occurs with a lag — the strategy requires several months of sustained relative performance to shift allocation materially.</p>
</section>
<section id="backtest-results" class="level2">
<h2 class="anchored" data-anchor-id="backtest-results">Backtest results</h2>
<p>The strategy was backtested from 2002 to March 2026 using Yahoo Finance continuous futures data. All signals are lagged one day to prevent look-ahead bias. The common analysis start date is 2003-08-18, reflecting the warm-up period required for the longest signal windows to initialize.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th>Strategy</th>
<th>ES benchmark</th>
<th>ES-only (levered)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Total return</td>
<td>3,699%</td>
<td>601%</td>
<td>2,250%</td>
</tr>
<tr class="even">
<td>CAGR</td>
<td>16.8%</td>
<td>8.6%</td>
<td>14.3%</td>
</tr>
<tr class="odd">
<td>Ann. volatility</td>
<td>22.3%</td>
<td>19.0%</td>
<td>23.4%</td>
</tr>
<tr class="even">
<td>Sharpe ratio</td>
<td><strong>0.807</strong></td>
<td>0.530</td>
<td>0.689</td>
</tr>
<tr class="odd">
<td>Sortino ratio</td>
<td><strong>1.095</strong></td>
<td>0.745</td>
<td>0.936</td>
</tr>
<tr class="even">
<td>Max drawdown</td>
<td><strong>−30.2%</strong></td>
<td>−57.1%</td>
<td>−42.4%</td>
</tr>
</tbody>
</table>
<p>The strategy produces a Sharpe of 0.807 and Sortino of 1.095 over the full backtest period, compared to 0.530 and 0.745 for the ES buy-and-hold benchmark. The maximum drawdown of −30.2% compares favorably to −57.1% for the benchmark and −42.4% for the levered ES-only alternative.</p>
<p>The comparison against the levered ES-only alternative is the more informative benchmark. It isolates the contribution of tactical allocation: the ES-only levered alternative applies the same dynamic leverage but holds only ES, producing a CAGR of 14.3% and Sharpe of 0.689. The additional 2.5 percentage points of CAGR and 0.118 Sharpe points above that baseline reflect the value of rotating across the alternative instruments.</p>
</section>
<section id="parameter-robustness" class="level2">
<h2 class="anchored" data-anchor-id="parameter-robustness">Parameter robustness</h2>
<p>A strategy that performs well only at its exact design parameters is a backtest artifact rather than a robust investment program. Two complementary analyses address this.</p>
<p>The <strong>Monte Carlo analysis</strong> used Latin Hypercube sampling to test 50 randomly chosen combinations across the full six-dimensional parameter space, with all combinations evaluated over the same common analysis start date to ensure a fair comparison. 52% of combinations produced a Sharpe above 0.70 — a level representing a meaningful positive risk-adjusted return that would justify the strategy’s operational cost over a passive alternative. The baseline sits at the 98th percentile of the distribution.</p>
<div id="ed7f6851" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_strategy_implementation_files/figure-html/cell-3-output-1.png" width="883" height="448" class="figure-img"></p>
<figcaption>Distribution of Sharpe ratios across 50 randomly sampled parameter combinations. Common analysis start: 2003-08-18. The baseline configuration (dashed black, Sharpe 0.807) sits at the 98th percentile. 52% of combinations exceed the 0.70 threshold. Source: Author calculations.</figcaption>
</figure>
</div>
</div>
</div>
<p>The most important finding is the dominant role of the signal lookback window. Shorter lookback windows consistently outperform longer ones — the correlation between window length and Sharpe across the Monte Carlo sample is −0.77. The current baseline window may be slightly longer than optimal, and a shorter window is a candidate for a future design revision pending out-of-sample confirmation from live deployment.</p>
<div id="ad867111" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_strategy_implementation_files/figure-html/cell-4-output-1.png" width="595" height="499" class="figure-img"></p>
<figcaption>Monte Carlo equity paths — 50 parameter combinations over the common analysis period. Black = baseline. Color = Sharpe ratio (green = higher, red = lower). All combinations trend upward throughout the sample. Source: Author calculations.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="regime-decomposition" class="level2">
<h2 class="anchored" data-anchor-id="regime-decomposition">Regime decomposition</h2>
<p>The strategy’s performance is not uniform across macro conditions. The regime decomposition classifies each trading day into one of four regimes using observable FRED data and evaluates performance within each.</p>
<div id="dcfbc6b2" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_strategy_implementation_files/figure-html/cell-5-output-1.png" width="614" height="499" class="figure-img"></p>
<figcaption>Macro regime classification across the backtest period, 2003–2026. Top panel: strategy equity curve with regime shading. Lower panels: the S&amp;P 500 12-month return, VIX, and CPI year-on-year used to classify regimes. Source: FRED, author calculations.</figcaption>
</figure>
</div>
</div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Regime</th>
<th>Days</th>
<th>% Sample</th>
<th>CAGR</th>
<th>Sharpe</th>
<th>Max DD</th>
<th>Win rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Equity Bull</td>
<td>837</td>
<td>14.1%</td>
<td>+82.2%</td>
<td>3.27</td>
<td>−21.8%</td>
<td>58.9%</td>
</tr>
<tr class="even">
<td>Equity Bear</td>
<td>657</td>
<td>11.0%</td>
<td>−39.1%</td>
<td>−2.03</td>
<td>−22.5%</td>
<td>46.9%</td>
</tr>
<tr class="odd">
<td>Inflation</td>
<td>575</td>
<td>9.7%</td>
<td>+7.5%</td>
<td>0.34</td>
<td>−28.8%</td>
<td>53.2%</td>
</tr>
<tr class="even">
<td>Neutral</td>
<td>3884</td>
<td>65.2%</td>
<td>+19.9%</td>
<td>0.90</td>
<td>−24.5%</td>
<td>56.9%</td>
</tr>
</tbody>
</table>
<p>The strategy earns its return primarily in two regimes. The Neutral regime — 65% of all trading days — produces a Sharpe of 0.90 and forms the backbone of compounded long-run performance. Equity Bull periods produce an exceptional Sharpe of 3.27. Together these two regimes account for 79% of the sample and all positive contribution.</p>
<p>The strategy loses money during Equity Bear periods at an annualized rate of −39.1%. This is the primary weakness of the design and is structural: the allocation signal is backward-looking and requires sustained deterioration before it reduces equity exposure materially. In sharp, rapid bear markets the strategy experiences full equity drawdown before the signal has time to act. An investor in this strategy should understand that bear market losses are the price of sustained equity participation across the 79% of time when conditions are favorable.</p>
<div id="f280e329" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_strategy_implementation_files/figure-html/cell-6-output-1.png" width="754" height="499" class="figure-img"></p>
<figcaption>Strategy performance by macro regime: CAGR, Sharpe, maximum drawdown, and daily win rate. The Neutral regime (grey) is the backbone of long-run return. Bear regime losses (red) are structural and expected given the signal’s backward-looking design. Source: FRED, author calculations.</figcaption>
</figure>
</div>
</div>
</div>
<p>The Inflation regime result — 7.5% CAGR and 0.34 Sharpe — is mediocre. The strategy has no explicit inflation protection mechanism. Gold allocation during inflation periods reflects only the signal’s backward-looking relative performance assessment, which may lag actual inflation dynamics. This is a known design gap.</p>
</section>
<section id="return-sources" class="level2">
<h2 class="anchored" data-anchor-id="return-sources">Return sources</h2>
<p>The strategy’s return comes from three sources operating simultaneously.</p>
<p>The dominant source is equity market exposure. The strategy maintains permanent net long equity through its ES core, and this exposure to the equity risk premium is the foundation of its long-run return. This is not alpha — it is the return available to any investor holding equity futures through their volatility.</p>
<p>The second source is real asset exposure through gold and silver. The factor attribution shows that the strategy carries a meaningful and persistent gold beta throughout the backtest period. This reflects the IR signal’s tendency to allocate to gold during periods when it outperforms ES — which tends to occur during equity stress and late-cycle environments.</p>
<p>The third source is the tactical rotation signal itself — the incremental return above a static long equity and gold position that comes from adjusting allocations dynamically based on relative performance. The full-sample analysis estimates this contribution at approximately 6 percentage points of annualized return, with a t-statistic that is meaningful but not conclusive given the backtest length. This is the component that requires ongoing validation in live deployment.</p>
<p>The strategy is a leveraged equity program with a real asset overlay and a tactical rotation mechanism — not a market-neutral or low-beta program. Its market exposure is dynamic, averaging approximately 1.25 times the equity market across the backtest period, rising above 2.0 during strong signal environments and falling toward 0.2 during weak signal periods.</p>
</section>
<section id="live-deployment" class="level2">
<h2 class="anchored" data-anchor-id="live-deployment">Live deployment</h2>
<p>The ES Core Relative Allocation has been deployed live on Darwinex Zero under the ticker UJNU since 5 March 2026.</p>
<p>Darwinex Zero applies a VaR normalization filter to all strategy returns before publishing them as a DARWIN index, standardizing the risk profile to a target VaR of 6.5% per month. Published DARWIN returns will therefore differ from the underlying strategy returns depending on how far actual volatility diverges from that target. The underlying strategy’s risk management operates independently of this filter.</p>
<p>Eight weeks of live trading is too short for any statistical inference about performance quality. What it confirms is that the implementation is functioning as designed — position generation, order sizing, and rebalancing mechanics are operating consistently with the backtested strategy. The appropriate evaluation horizon for drawing meaningful conclusions is a minimum of 24 months of live trading across at least two distinct macro regimes.</p>
<p>The live track record will be updated on the connected Darwinex Zero performance page as it accumulates.</p>
</section>
<section id="the-framework-applied" class="level2">
<h2 class="anchored" data-anchor-id="the-framework-applied">The framework applied</h2>
<p>Every design decision in the ES Core Relative Allocation traces back to a specific section of this framework. The return source taxonomy from section 3 explains what the strategy harvests. The portfolio construction principles from section 4 explain how exposures are sized and combined. The expected return framework from section 5 explains how to evaluate whether current conditions justify the positions. The cost hierarchy from section 6 explains where the strategy sits in a broader portfolio — as a justified active program alongside a passive core, not as a replacement for one.</p>
<p>That connection is what distinguishes a documented investment process from a backtest report. The standards are stated in advance. The evidence is presented honestly. The gaps are acknowledged. What remains is the live record.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>